### ISSUE TITLE
Issue on login - "KeyError: 'Token'

### ISSUE THREAD

**Issue by Joe1010101** [NathanRLiu/Discord-AutoMessage#3]
Hi,

I'm trying to use the module however I'm experiencing an issue with regards to the captcha/site key as left below. I'd appreciate any help as I have read through all the relevant documentation but cannot see a place to save a captcha provider key.

{"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"}
Traceback (most recent call last):
  File "C:\Users\userhere\Desktop\Discord Automesseger\Discord-AutoMessage-main\discord_automessage.py", line 30, in <module>
    daToken = eval(loginResponse.text)["Token"]
KeyError: 'Token'

Thanks again.

**Comment by deetoomoo** [comment]
Try to log in normally with your account first to clear the captcha before using interacting with discord through API.

**Comment by BNegetive** [comment]
> 

i'm getting the same message, and i'v been logged in in all browsers i have
if i switch this line
daToken = eval(loginResponse.text)["token"]
with hardcoded token i take from chrome, like this
daToken = "mfa.some long token"

it works for me, but we tried to do if for a friend of mine, and it doesn't work for him, so what do you mean login normally with your account? he's logged in on all browsers as well...

**Comment by NathanRLiu** [comment]
Sorry if this seems obvious but before I think of anything else I just wanna make sure that your friend is using his own token and not yours, could you confirm that for me?

**Comment by BNegetive** [comment]
> Sorry if this seems obvious but before I think of anything else I just wanna make sure that your friend is using his own token and not yours, could you confirm that for me?

Yes, we tried to use tokens from all his browsers, and it didn't work

**Comment by NathanRLiu** [comment]
> > Sorry if this seems obvious but before I think of anything else I just wanna make sure that your friend is using his own token and not yours, could you confirm that for me?
> 
> Yes, we tried to use tokens from all his browsers, and it didn't work

Maybe try having him sign out and then sign in again from a browser?
