### ISSUE TITLE
Can my DaMessage string be a text file?

### ISSUE THREAD

**Issue by Auditormadness9** [NathanRLiu/Discord-AutoMessage#5]
The message I want to leave is actually large and has multiple formatting instances and linebreaks and I don't think it'll be comfortable to write all of it on one line between brackets in the code, hence thought... is it possible to put it in a text file then somehow have it reference to that file? (which will obviously be placed in the project directory)

Thanks in advance!

**Comment by NathanRLiu** [comment]
Definitely! I found this article that will teach you how to do it. https://www.w3schools.com/python/python_file_open.asp Let me know if this helps so I can mark the issue as resolved, or if you need more help.

**Comment by NathanRLiu** [comment]
Another option is to enclose the string within three quotation marks directly in your Python code. This allows you to create readable multiline strings.
